tools:
  php_analyzer:
    config:
      metrics_coupling:
        stable_code:
          namespace_prefixes:
            - SetBased\Stratum\MySql\Wrapper

filter:
  dependency_paths:
    - "vendor/"
  excluded_paths:
    - 'test/'

build:
  environment:
    mysql: 5.7
    php:
      pecl_extensions:
        - inotify

  project_setup:
    before:
      - mysql --version
      - mysql -u root -e "set global binlog_format = 'row';"
      - mysql -u root -e "set global log_bin_trust_function_creators = 1;"

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    coverage:
      tests:
        override:
          - command: './bin/phing unit'
            coverage:
              file:   'test/coverage.xml'
              format: 'php-clover'
