/**
 * Test for column%sort v.s. column%type.
 *
 * @param p_tst_last_name  Can be a long string.
 * @param p_tst_first_name Can be a long string.
 * @param p_tst_instrument Can be a long string.
 *
 * @type row0
 */
create procedure tst_test_parameter_sort(p_tst_last_name  @tst_sort.tst_last_name%sort@,
                                         p_tst_first_name @tst_sort.tst_first_name%sort@,
                                         p_tst_instrument @tst_sort.tst_instrument%sort@)
reads sql data
begin
  select *
  from   TST_SORT
  where  tst_last_name  = ifnull(p_tst_last_name, tst_last_name)
  and    tst_first_name = ifnull(p_tst_first_name, tst_first_name)
  and    tst_instrument = ifnull(p_tst_instrument, tst_instrument)
  ;
end
